# This file reads from "comicsData.csv" (generated by "webScrapeMayo.py") located in the same directory as this file
# This file calculates and aggregates statistics on Marvel Comics based on "comicsData.csv"
# This file generates "marvelData.xlsx" saved to the same directory as this file


import csv
from openpyxl import Workbook

# PARAM: deltaDict - a dictionary (keys: item code, values: delta value)
# PARAM: itemCode - a specific item code in the deltaDict dictionary
# RETURN: the "rank" of itemCode within all values in deltaDict (rank 1 = highest delta value)
def deltaRank(deltaDict, itemCode):
	ranked = sorted(deltaDict, key=deltaDict.get, reverse=True)
	rank = ranked.index(itemCode)
	rank += 1
	return rank

# list of dictionaries
	# dictionary key: 'year' ; value: year (4-digit)
	# dictionary key: 'month' ; value: month (numeric)
	# dictionary keys: 'topIss', 'topNumOne', 'topReord', & 'topDelta' ; value: dictionary
		# dictionary key: 'data' ; value: dictionary - full row of issue data from "comicsData.csv"
		# dictionary key: 'rank' ; value: overall rank (considering non-Marvel comics) within the top type
marvelData = []

# comicsData.csv headers: 'year', 'month', 'quantity rank', 'item code', 'price', 'publisher', 'title', 'issue', 'reorder', 'estimated sales', 'delta'
with open('comicsData.csv', 'r') as comics:
	reader = csv.DictReader(comics)

	for row in reader:
		# check to see if the row's date (month & year combination) has an existing entry in marvelData
		if row['month'] not in [partial['month'] for partial in marvelData if partial['year'] == row['year']]:
			# if not the first entry in marvelData, add the delta rank to the last appended marvelData entry
			if len(marvelData) != 0:
				marvelData[-1]['topDelta']['rank'] = deltaRank(deltaData, marvelData[-1]['topDelta']['data']['item code'])
			
			marvelData.append({
				'year': row['year'],
				'month': row['month'],
				'topIss': {'data': {}, 'rank': 0},
				'topNumOne': {'data': {}, 'rank': 0},
				'topReord': {'data': {}, 'rank': 0},
				'topDelta': {'data': {}, 'rank': 0}
			})
			
			numOneCt = 0
			reordCt = 0
			deltaTemp = -500000
			deltaData = {}

		# Increase counts
		if row['issue'] == '1':
			numOneCt += 1
		if row['reorder']:
			reordCt += 1
		if row['delta']:
			deltaData[row['item code']] = int(row['delta'])

		# Set data for top monthly Marvel issue
		if marvelData[-1]['topIss']['rank'] == 0 and row['publisher'] == 'Marvel Comics':
			marvelData[-1]['topIss']['data'] = row
			marvelData[-1]['topIss']['rank'] = int(row['quantity rank'])

		# Set data for top monthly Marvel first issue
		if marvelData[-1]['topNumOne']['rank'] == 0 and row['publisher'] == 'Marvel Comics' and row['issue'] == '1':
			marvelData[-1]['topNumOne']['data'] = row
			marvelData[-1]['topNumOne']['rank'] = numOneCt
		
		# Set data for top monthly reordered Marvel issue
		if marvelData[-1]['topReord']['rank'] == 0 and row['publisher'] == 'Marvel Comics' and row['reorder']:
			marvelData[-1]['topReord']['data'] = row
			marvelData[-1]['topReord']['rank'] = reordCt

		# Set data for top monthly Marvel delta
		if row['delta'] and deltaTemp < int(row['delta']) and row['publisher'] == 'Marvel Comics':
			marvelData[-1]['topDelta']['data'] = row
			deltaTemp = int(row['delta'])

	# add the delta rank to the last marvelData entry
	marvelData[-1]['topDelta']['rank'] = deltaRank(deltaData, marvelData[-1]['topDelta']['data']['item code'])

# create and save data to "marvelData.xlsx"
typesKey = {
	'Top Issue': 'topIss',
	'Top First Issue': 'topNumOne',
	'Top Reorder': 'topReord',
	'Highest Delta': 'topDelta'
}
wb = Workbook()
ws = wb.active
ws.title = 'Top Months'
for item in marvelData:
	# create a worksheet for each date (month & year combination)
	sheet = wb.create_sheet(title=item['year']+'_'+item['month'])

	# generate a header row
	header = ['type', 'rank']
	header.extend(item['topIss']['data'].keys())
	sheet.append(header)

	# save each row of data for the 4 top types
	for topType in typesKey:
		values = [topType, item[typesKey[topType]]['rank']]
		values.extend(list(item[typesKey[topType]]['data'].values()))
		sheet.append(values)
	
	# if all of the topType ranks for a given date are value '1', save that date to the "Top Months" worksheet
	if len(set([item[partial]['rank'] for partial in item if partial.startswith('top')]).difference({1})) == 0:
		ws.append([item['year'], item['month']])
	
wb.save('marvelData.xlsx')