# This file reads from "marvelData.xlsx" (generated by "calculateMarvel.py") located in the same directory as this file
# This file reads .JSON files (generated by "marvelAPI.py") located in the 'records' directory
# This file requires API & access keys for the Twitter API (https://developer.twitter.com/en/docs/twitter-api) on lines 71 - 74
# This file uses issues saved in "marvelData.xlsx" and records pulled from the Marvel API to generate a tweet featuring a "top" Marvel comic from any year and the current month
# This file generates image files saved in an 'images' folder located in the same directory as this file
# This file generates a Twitter post


import json
import random
from openpyxl import load_workbook
import datetime
import tweepy
import urllib.request


wb = load_workbook('marvelData.xlsx')

# select random record from the current month and any year
year = random.randint(2003, 2020)
month = datetime.datetime.now().month
try:
	sheet = wb[f"{year}_{month}"]
except:
	# force a valid year/month combination by removing incomplete years
	year = random.randint(2004, 2019)
	sheet = wb[f"{year}_{month}"]
	
row = random.randint(2, 5)
marvelId = sheet.cell(row = row, column = 14).value
# check for edge case of no API record found / saved
while not marvelId:
	row = random.randint(2, 5)
file = f"records/{marvelId}.json"

# pull data from API .JSON record
with open(file, 'r') as comic:
	data = json.load(comic)

	title = data['title']
	imgPath = data['images'][0]['path']
	imgExt = '.' + data['images'][0]['extension']
	for link in data['urls']:
		if link['type'] == 'detail':
			url = link['url']
	creators = {}
	for creator in data['creators']['items']:
		creators[creator['name']] = creator['role']

# build text for tweet
text = ''
yearDiff = datetime.datetime.now().year - year
if yearDiff == 1:
	text = "Last year on this month, "
else:
	text = f"{yearDiff} years ago on this month, "
text += title
if row == 2:
	text += ' was the top selling issue published by Marvel Comics.'
elif row == 3:
	text += ' was the top selling first issue published by Marvel Comics.'
elif row == 4:
	text += ' was the most reordered issue published by Marvel Comics.'
else:
	delta = '{:,}'.format(int(sheet.cell(row = row, column = 13).value))
	text += ' sold ' + delta + ' more copies than the previous issue.'

creatorText = title + ' Creative team: '
for creator in creators:
	creatorText += f"{creator} ({creators[creator]}), "
# remove ', ' from after the last appended creator
creatorText = creatorText[:len(creatorText)-2]

# pull image
img = imgPath + imgExt
filename = f"images/{marvelId}{imgExt}"
urllib.request.urlretrieve(img, filename)

# twitter integration
apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' # API KEY: REQUIRED
secrcetAPI = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' # SECRET API KEY: REQUIRED
accessKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' # ACCESS KEY: REQUIRED
secretAccess = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' # SECRET ACCESS KEY: REQUIRED

auth = tweepy.OAuthHandler(apiKey, secrcetAPI)
auth.set_access_token(accessKey, secretAccess)
api = tweepy.API(auth)

tweetText = text + '\n\n' + creatorText + '\n\n' + url
twitterImg = api.media_upload(filename)
# post the tweet
try:
	api.update_status(tweetText, media_ids = [twitterImg.media_id])
	# non-media tweet
	# api.update_status(tweetText)
# remove creator text if tweet is too long
except:
	tweetText = text + '\n\n' + url
	api.update_status(tweetText, media_ids = [twitterImg.media_id])
	# non-media tweet
	# api.update_status(tweetText)